---
  # Tasks: ansible-role-login-screen
  #
  # Author: Luc Rutten
  # Version: 1.0
  #

  - name: "Create directory when not exist"
    file:
      path: /opt/scripts
      state: directory
      owner: root
      group: root
      mode: 0754

  - name: "Copy template banner.sh.j2"
    template:
      src: banner.sh.j2
      dest: /opt/scripts/banner.sh
      owner: root
      group: root
      mode: 0754

  - name: "Add /opt/scripts/banner.sh to /etc/rc.local for automatic update banner on startup"
    blockinfile:
      path: /etc/rc.local
      backup: yes
      marker: "# {mark} MANAGED BY ANSIBLE - Banner update on startup"
      insertbefore: "exit 0"
      block: |
        /opt/scripts/banner.sh
      state: present

  - name: "Add chvt 1 to /etc/rc.local for fix for showing login screen"
    blockinfile:
      path: /etc/rc.local
      marker: "# {mark} MANAGED BY ANSIBLE - Fix for showing login screen"
      backup: yes
      insertbefore: "exit 0"
      block: |
        chvt 1
      state: present
